### ISSUE TITLE
contract-state-stream tests failing

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-utils#108]
First raised in https://github.com/trufflesuite/drizzle-utils/pull/107#issuecomment-494434837

**Comment by adrianmcli** [comment]
It seems like the tests are passing if you look at a recent build I triggered here: https://travis-ci.org/trufflesuite/drizzle-utils/builds/543404647

@honestbonsai Can you do a sanity check to make sure I'm not hallucinating?

**Comment by honestbonsai** [comment]
The Node 11 and Node LTS look fine. Node 12 seems to be a recurring issue @adrianmcli

**Comment by adrianmcli** [comment]
Ah yeah, that's a separate issue with Ganache and Web3's dependency on Scrypt. Because Scrypt just does not work on v12 Node anymore.

<img width="380" alt="Screen Shot 2019-06-11 at 1 06 25 AM" src="https://user-images.githubusercontent.com/943555/59208995-49984b80-8be5-11e9-8d31-cfef4a39ab82.png">


Ganache-Core issue here: https://github.com/trufflesuite/ganache-core/issues/425
Scrypt.js issue here: https://github.com/axic/scrypt.js/issues/5

I'm not sure what we can do about it at this point.

**Comment by adrianmcli** [comment]
Closing because this is a separate issue.
