### ISSUE TITLE
Polish contract-event-stream

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-utils#68]
Refactor and add README

**Comment by adrianmcli** [comment]
- [ ] Remove this [comment](https://github.com/trufflesuite/drizzle-utils/blob/master/packages/contract-event-stream/index.js#L13) since it's already [solved](https://github.com/trufflesuite/drizzle-utils/blob/master/packages/core/index.js#L28) in core

**README**

- [ ] Show usage example with artifact
- [ ] Show usage example with contract instance

**Comment by adrianmcli** [comment]
I need to look at this before EthCon Korea on May 27.
