### ISSUE TITLE
Polish current-account-stream

### ISSUE THREAD

**Issue by honestbonsai** [trufflesuite/drizzle-utils#70]
Refactor and add README

**Comment by adrianmcli** [comment]
There are no tests for this package, mostly because we'd have to simulate MetaMask usage with an e2e test. That might be too high effort for this stage of development, especially since this is pretty easily testable manually.

Maybe we can simplify the README a bit by removing the bit about RxJS since it's kind of implied that all packages in this monorepo with the name `stream` in it is RxJS.
